### ISSUE TITLE
Change on joemonster layout

### ISSUE THREAD

**Issue by maq-pl** [szymex/joemonster-xbmc-plugin#2]
Hi,
first I'd like to thank you for this plugin, I use it for some time and it's great feature :)

Few day's ago joemonster changed sourcecode. I'm not good at python at all, but I've made change to make your plugin work and make few additions to support videos from Vimeo, dailymotion and myepicwall which weren't supported.

I don't know how to contact you or paste my changes, so I write here for contact / info about adding changes.

**Comment by szymex** [comment]
Fixed.
